name: CI/CD Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy via SSH & Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            sudo docker stop webapp || true
            sudo docker rm webapp || true
            cd ~/webapp || mkdir ~/webapp && cd ~/webapp
            cat > index.html << 'EOT'
            <!DOCTYPE html>
            <html>
            <body>
              <h1>Auto Deployed by GitHub Actions</h1>
              <p>Updated on $(date)</p>
            </body>
            </html>
            EOT
            cat > Dockerfile << 'EOT'
            FROM nginx:latest
            COPY index.html /usr/share/nginx/html/
            EXPOSE 80
            CMD ["nginx","-g","daemon off;"]
            EOT
            sudo docker build -t github-webapp .
            sudo docker run -d -p 80:80 --name webapp github-webapp
          EOF
